import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/HomePage.module.css";
import { useState, useEffect, useRef } from 'react';
import CalendarCard from "@/components/CalendarCard";
import TopBar from "@/components/TopBar";
import SettingIcon from "@/components/SettingIcon";
import LinkButton from "@/components/LinkButton";
import FavouriteButton from "@/components/FavouriteButton";
import Weather from "@/components/Weather";
import Navigation from "@/components/Navigation";
import MeditationCardHome from "@/components/MeditationCardHome";
import { meditationData } from '@/data/meditation';
import lottie from "lottie-web";

export default function HomePage() {
    const [loaded, setLoaded] = useState(false);
    const [currentDate, setCurrentDate] = useState('');
    const data = meditationData.meditations;
    const loading = useRef(null);

    useEffect(() => {
        const date = new Date();
        const options = { month: 'long', day: 'numeric', year: 'numeric' };
        const formattedDate = date.toLocaleDateString('en-US', options);
        setCurrentDate(formattedDate);
    }, []);

    useEffect(() => {
        const hasVisitedBefore = localStorage.getItem('hasVisitedHomePage');
        if (!hasVisitedBefore) {
            setTimeout(() => {
                setLoaded(true);
                localStorage.setItem('hasVisitedHomePage', 'true');
            }, 5000);
        } else {
            setLoaded(true);
        }
    }, []);

    useEffect(() => {
        const anim = lottie.loadAnimation({
            container: loading.current,
            renderer: 'svg',
            loop: true,
            autoplay: true,
            path: "/animations/loading.json"
        });

        return () => {
            anim.destroy();
        };
    }, []);

    return (
        <>
            <Head>
                <title>Tranquify App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <div className={styles.content}>
                    {!loaded ? ( 
                        <div className={styles.loading}>
                            <div className={styles.logo}>
                                <div ref={loading} />
                            </div>
                            <h1 className={styles.text}>Loading...</h1>
                            
                        </div>
                    ) : (
                        <div className={styles.homePageContent}>
                            <div className={styles.topBar}>
                                <SettingIcon />
                            </div>
                            <div className={styles.content}>
                                <div className={styles.greetingsContainer}>
                                    <Weather setLoaded={setLoaded} />
                                </div>
                                <div className={styles.calendar}>
                                    <CalendarCard i="4" icon="/images/terrible-icon.svg" link="/moodRecord" iconIndex={4}/>
                                    <CalendarCard i="3" icon="/images/ok-icon.svg" link="/moodRecord" iconIndex={2}/>
                                    <CalendarCard i="2" icon="/images/add-calendar.svg" link="/mood"/>
                                    <CalendarCard i="1" icon="/images/great-icon.svg" link="/moodRecord" iconIndex={0}/>
                                    <CalendarCard i="0" icon="/images/add-calendar.svg" link="/mood"/>
                                </div>
                                <hr className={styles.divideLine}/>
                                <div className={styles.meditationContainer}>
                                    <div className={styles.meditation}>
                                        <h2>Meditation for you</h2>
                                        <LinkButton link="/meditation" linkText="View more"/> 
                                    </div>
                                    <div className={styles.meditationCards}>
                                        <MeditationCardHome title={data[0].title} link={data[0].thumbnail} meditation={0}/>
                                        <MeditationCardHome title={data[2].title} link={data[2].thumbnail} meditation={2}/>
                                        <MeditationCardHome title={data[6].title} link={data[6].thumbnail} meditation={6}/>
                                        <div className={styles.meditationLastCard}>
                                            <MeditationCardHome title={data[1].title} link={data[1].thumbnail} meditation={1}/>
                                        </div>
                                        {/* <MeditationCardHome link="/images/thumbnails/2.png" title="Meditation"/>
                                        <MeditationCardHome link="/images/thumbnails/3.png" title="Meditation"/>
                                        <MeditationCardHome link="/images/thumbnails/4.png" title="Meditation"/> */}
                                    </div>
                                </div>
                                <div className={styles.favourites}>
                                    <FavouriteButton link="/meditationFavourite"/>
                                </div>
                                <Navigation/>
                            </div>
                        </div>
                    )}
                </div>
            </main>
        </>
    );
}
