import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import TopBar from "@/components/TopBar";
import GreenButton from "@/components/GreenButton";
import BeigeButton from "@/components/BeigeButton";
import LinkButton from "@/components/LinkButton";
import {useRouter} from "next/router";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Tranquify</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
          <Image 
            src="/images/logo-colour.svg"
            alt="logo"
            width={268} height={268} 
            className={styles.logo}
          />
        <div className={styles.buttonContainer}>
          <GreenButton id="page.index.log.in.button" greenButtonText="Log in" greenButtonLink="/logIn" />
          <BeigeButton beigeButtonText="Sign up" beigeButtonLink="signUp" /> 
        </div>
        <div className={styles.linkContainer}>
          <LinkButton link="/onboarding" linkText="Continue as guest" />
        </div>
        
      </main>
    </>
  );
}
