import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/LogIn.module.css";
import TopBar from "@/components/TopBar";
import GreenButton from "@/components/GreenButton";
import BeigeButton from "@/components/BeigeButton";
import LinkButton from "@/components/LinkButton";


export default function LogIn() {
    return (
        <>
            <Head>
                <title>Tranquify App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <TopBar/>
            <main className={`${styles.main}`}>
                <div className={styles.content}>
                    
                </div>
            </main>
        </>
    );
}
