import Head from "next/head";
import styles from "@/styles/MeditationPlayer.module.css";
import TopBar from "@/components/TopBar";
import GreenButton from "@/components/GreenButton";
import { useRouter } from "next/router";
import { meditationData } from "@/data/meditation";
import YouTube from 'react-youtube';
import Image from 'next/image';
import { useState } from "react";

export default function MeditationPlayer() {
    const router = useRouter();
    const meditationContentId = Number(router.query.media);
    const data = meditationData.meditations[meditationContentId];
    if (!data || !data.source) {
        return <div>Loading...</div>;
    }

    //for the YouTube player
    const opts = {
        height: '217',
        width: '319',
        playerVars: {
            autoplay: 1,
        },
    };

    //save button
    const [isSaved, setIsSaved] = useState("./images/unsaved-icon-green.svg");
    function heartClickHandler(e) {
        isSaved === './images/unsaved-icon-green.svg' ? setIsSaved('./images/saved-icon-green.svg') : setIsSaved('./images/unsaved-icon-green.svg');
        // e.stopPropagation();
        e.preventDefault();
    }
    return (
        <>
            <Head>
                <title>Tranquify App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={`${styles.main}`}>
                <div className={styles.content}>
                    <div className={styles.meditation}>
                        <YouTube videoId={data.source} opts={opts} />
                        <div className={styles.textContainer}>
                            <div className={styles.titleContainer}>
                                <h2 className={styles.title}>{data.title}</h2>
                                <div onClick = {(e) => { heartClickHandler(e)}} className={styles.saveIcon}>
                                    <Image src={isSaved} alt='heart icon' width={22} height={20} />
                                </div>
                            </div>
                            <p>{data.duration}min</p>
                            <p>{data.description}</p>
                        </div>
                    </div>
                    <div className={styles.button} onClick={() => router.back()}>
                        <GreenButton greenButtonText="Finish Meditation" greenButtonLink="#" />
                    </div>
                </div>
            </main>
        </>
    );
}
