import Head from "next/head";
import styles from "@/styles/Result.module.css";
import TopBar from "@/components/TopBar";
import GreenButton from "@/components/GreenButton";
import Image from "next/image";
import { useRouter } from "next/router";
import Navigation from "@/components/Navigation";

export default function ResultLow() {
    const moodMascots = ['/images/terrible-mascot.svg', '/images/bad-mascot.svg', '/images/ok-mascot.svg', '/images/good-mascot.svg', '/images/great-mascot.svg']
    const moodMascotsAlt = ['Terrible mood mascot', 'Bad mood mascot', 'Okay mood mascot', 'Good mood mascot', 'Great mood mascot']
    const router = useRouter();
    const moodScore = Number(router.query.mood);
    const totalScore =  Number(router.query.totalScore);
    console.log(router.query);

    const suggestion01 = ["Gratitude Practice: Reflect on the positives of your day and practice gratitude. This can further enhance your mood and well-being.", "Positive Affirmations: Practice positive affirmations to reinforce your good day and alleviate any mild stress.", " Sleep Routine: Establish a calming bedtime routine. Avoid screens before bed and create a soothing environment to improve sleep quality."]
    const suggestion02 = [" Mindful Relaxation: Engage in mindful relaxation exercises. Consider deep breathing or yoga to maintain your positive state of mind.", "Consistent Sleep Schedule: Aim for a consistent sleep schedule. Go to bed and wake up at the same time daily to improve overall sleep quality.", " Reflective Journaling: Spend a few minutes jotting down your thoughts or feelings from the day. This can help in processing emotions and promoting better sleep."]

    return (
        <>
            <Head>
                <title>Tranquify App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={`${styles.main}`}>
                <div className={styles.content}>
                    <div className={styles.resultCard}>
                        <div className={styles.mascot}>
                            <Image src={moodMascots[moodScore - 1]} alt={moodMascotsAlt[moodScore - 1]} width={100} height={130} />
                        </div>
                        <p className={styles.suggestionTitle}>Suggestions for You</p>
                        <div className={styles.suggestion}>
                            <div className={styles.checkMarkIcon}>
                                <Image src='./images/checkmark.svg' alt='checkmark icon' width={20} height={20} />
                            </div>
                            <div className={styles.suggestionText}>
                                {totalScore >= 4 && totalScore <= 10 ? suggestion01[0]
                                    : totalScore >= 11 && totalScore <= 15? suggestion01[1]
                                    : suggestion01[2]}
                            </div>
                        </div>

                        <div className={styles.suggestion}>
                            <div className={styles.checkMarkIcon}>
                                <Image src='./images/checkmark.svg' alt='checkmark icon' width={20} height={20} />
                            </div>
                            <div className={styles.suggestionText}>
                                {totalScore >= 4 && totalScore <= 10 ? suggestion02[0]
                                    : totalScore >= 11 && totalScore <= 15? suggestion02[1]
                                    : suggestion02[2]}
                            </div>
                        </div>
                    </div>
                    <div className={styles.meditationButton}>
                        <GreenButton greenButtonText="Start Meditation" greenButtonLink="/meditation"/>
                    </div>
                    <div>
                        <Navigation />
                    </div>
                </div>
            </main>
        </>
    );
}
